---
deployment:
  tasks:
    - export DEPLOYPATH=/home/grupo2ze/public_html/
    - rm -Rf $DEPLOYPATH/* 
    - cp -Rf model $DEPLOYPATH
    - cp -Rf view $DEPLOYPATH
    - cp -Rf controller $DEPLOYPATH
    - cp -Rf index.html $DEPLOYPATH
    - cp -Rf giphy.gif $DEPLOYPATH
    - cp -Rf logo.gif $DEPLOYPATH